/*
 * SofaBuffers Kotlin Multiplatform — conformance against the shared, language-
 * agnostic test vectors (assets/test_vectors.json, generated by corelib-c-cpp).
 *
 * CORELIB_PLAN §7 requires every corelib to replay these exact vectors for both
 * encode and decode, plus the chunked, skip and roundtrip scenarios the vector
 * README lists. A failure names the vector it came from.
 *
 * WHICH COLUMN THIS REPO ASSERTS. Every test here drives the *primitive*
 * encoder/decoder against `serialized` — the dense image, the ground truth for the
 * raw wire layer this library implements. The sibling `serialized_sparse` column
 * is deliberately not read, and that is not a coverage gap: it is the
 * MESSAGE_SPEC §2 sparse-canonical image, produced by a *message* layer deciding
 * per field whether a value equals its declared default. This repo has no message
 * layer and no schema defaults, so it cannot produce that form and has nothing to
 * compare against; the generator's per-language conformance driver owns it. The
 * primitive-level half of §2 — a contentless sequence costing zero bytes — is
 * covered by EncoderTest's lazy-framing cases instead.
 *
 * SPDX-License-Identifier: MIT
 */
package org.sofabuffers.sofab

import java.io.File
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue

class VectorConformanceTest {

    private val vectors: List<JsonObject> = Vectors.positive
    private val invalidUtf8: List<JsonObject> = Vectors.invalidUtf8

    // --- encode: replay fields[] and compare to serialized.hex ---------------

    @Test
    fun encodeVectors() {
        for (v in vectors) {
            val offset = v.int("offset")
            val buf = ByteArray(4096)
            val os = OStream(buf, offset)
            for (f in v.arr("fields")) replay(os, f.jsonObject)
            assertEquals(v.serializedHex(), hex(buf, offset, offset + os.bytesUsed), "encode ${v.name()}")
        }
        assertTrue(vectors.size >= 80, "the shared suite carries the full vector set")
    }

    /**
     * §7.2 item 4: replay every vector into an encoder backed by a buffer far
     * smaller than the message plus a flush sink, forcing repeated mid-field
     * flushes, and get bytes identical to the one-shot encoding.
     */
    @Test
    fun chunkedEncodeVectors() {
        for (room in intArrayOf(Sofab.MIN_OUTPUT_BUFFER, 3, 7)) {
            for (v in vectors) {
                val collected = ArrayList<Byte>()
                val os = OStream(ByteArray(room), v.int("offset"), { data, off, len ->
                    for (i in off until off + len) collected.add(data[i])
                })
                for (f in v.arr("fields")) replay(os, f.jsonObject)
                os.flush()
                val out = collected.toByteArray()
                // The sink receives the reserved offset region too; the message
                // itself starts after it.
                assertEquals(
                    v.serializedHex(),
                    hex(out, v.int("offset"), out.size),
                    "chunked encode (buffer $room) ${v.name()}",
                )
            }
        }
    }

    // --- decode: feed serialized.hex and compare the event stream -------------

    @Test
    fun decodeVectors() {
        for (v in vectors) {
            val wire = unhex(v.serializedHex())
            val visitor = RecordingVisitor()
            val input = IStream()
            input.feed(wire, visitor)
            assertEquals(expectedEvents(v), visitor.events, "decode ${v.name()}")
            assertEquals(DecodeStatus.COMPLETE, input.status, "decode ${v.name()} consumes the message exactly")
        }
    }

    /**
     * The strongest guard on the streaming state machine: feed every vector one byte
     * at a time and in 3- / 7-byte chunks through a single decoder and assert the
     * event stream is identical to a single feed.
     */
    @Test
    fun chunkedDecodeVectors() {
        for (chunk in intArrayOf(1, 3, 7)) {
            for (v in vectors) {
                val wire = unhex(v.serializedHex())
                assertEquals(
                    expectedEvents(v),
                    decodeEventsChunked(wire, chunk),
                    "decode/${chunk}B ${v.name()}",
                )
            }
        }
    }

    /**
     * Skip-ids decoding: a receiver that ignores the vector's `skip_ids` (and, for a
     * sequence id, the whole sub-tree under it) must still recover every other
     * field, proving the decoder resyncs on the field after any skipped field or
     * sub-sequence at any nesting depth.
     */
    @Test
    fun skipIdsDecodeVectors() {
        var ran = 0
        for (v in vectors) {
            val skip = v["skip_ids"]?.jsonArray?.map { it.jsonPrimitive.content.toInt() }?.toSet() ?: continue
            ran++
            val wire = unhex(v.serializedHex())
            for (chunk in intArrayOf(0, 1, 3)) {
                val visitor = SkipVisitor(skip)
                val input = IStream()
                if (chunk == 0) {
                    input.feed(wire, visitor)
                } else {
                    var i = 0
                    while (i < wire.size) {
                        val n = minOf(chunk, wire.size - i)
                        input.feed(wire, i, n, visitor)
                        i += n
                    }
                }
                assertEquals(DecodeStatus.COMPLETE, input.status, "skip ${v.name()}")
                assertEquals(
                    expectedEventsWithSkip(v, skip),
                    visitor.out.events,
                    "skip ${v.name()} (chunk $chunk)",
                )
            }
        }
        assertTrue(ran > 0, "the suite carries skip_ids vectors")
    }

    /** Roundtrip: the decoded event stream survives an encode of the same ops. */
    @Test
    fun roundTripVectors() {
        for (v in vectors) {
            val buf = ByteArray(4096)
            val os = OStream(buf)
            for (f in v.arr("fields")) replay(os, f.jsonObject)
            val wire = buf.copyOf(os.bytesUsed)
            assertEquals(expectedEvents(v), decodeEvents(wire), "roundtrip ${v.name()}")
        }
    }

    /**
     * This corelib compiles in every wire feature — it has no `SOFAB_DISABLE_*`
     * switches — so no vector is skipped and `requires` is ignored by design. Guard
     * that the suite never introduces a capability tag this port has not been told
     * about, which would otherwise be silently treated as supported.
     */
    @Test
    fun requiresTagsAreKnown() {
        val known = setOf("fixlen", "array", "sequence", "fp64", "int64")
        for (v in vectors + invalidUtf8) {
            for (cap in v["requires"]?.jsonArray.orEmpty()) {
                assertTrue(cap.jsonPrimitive.content in known, "unknown capability tag in ${v.name()}: $cap")
            }
        }
    }

    // --- negative vectors: invalid UTF-8 (CORELIB_PLAN §6.4) -----------------

    @Test
    fun invalidUtf8PayloadsAreRejectedByTheValidator() {
        assertTrue(invalidUtf8.size >= 11, "the shared suite carries the invalid_utf8 set")
        for (v in invalidUtf8) {
            val payload = unhex(v.str("string_hex"))
            assertTrue(!Utf8.valid(payload), "Utf8.valid must reject ${v.name()}")
        }
    }

    @Test
    fun invalidUtf8IsRefusedOnEncode() {
        for (v in invalidUtf8) {
            assertEquals("invalid_argument", v.str("encode_outcome"), v.name())
            val payload = unhex(v.str("string_hex"))
            val id = v.int("id")
            val e = assertFailsWith<SofabException>(v.name()) {
                encode(256) { it.writeFixlen(id, payload, 0, payload.size, FixlenType.STRING) }
            }
            assertEquals(SofabError.ARGUMENT, e.error, v.name())
        }
    }

    @Test
    fun invalidUtf8IsRejectedOnDecodeWhenMaterialized() {
        // §6.4: validation runs where a string is MATERIALIZED, and the outcome must
        // not depend on where the chunk boundaries fell — a payload merely split
        // stays INCOMPLETE until it ends, then the complete payload is INVALID.
        for (v in invalidUtf8) {
            assertEquals("invalid", v.str("decode_outcome"), v.name())
            val wire = unhex(v.str("serialized_hex"))
            for (chunk in intArrayOf(0, 1, 2, 3)) {
                val input = IStream()
                val strict = MaterializingStringVisitor()
                val e = assertFailsWith<SofabException>("${v.name()} (chunk $chunk)") {
                    if (chunk == 0) {
                        input.feed(wire, strict)
                    } else {
                        var i = 0
                        while (i < wire.size) {
                            val n = minOf(chunk, wire.size - i)
                            input.feed(wire, i, n, strict)
                            i += n
                        }
                    }
                }
                assertEquals(SofabError.INVALID_MSG, e.error, v.name())
                assertEquals(DecodeStatus.INVALID, input.status, v.name())
            }
        }
    }

    @Test
    fun skippedFieldsAreNeverValidated() {
        // §6.4: skipping stays a length jump over bytes that are not inspected, so an
        // invalid-UTF-8 string nobody reads does not make the message INVALID.
        for (v in invalidUtf8) {
            val input = IStream()
            input.feed(unhex(v.str("serialized_hex")), object : Visitor {})
            assertEquals(DecodeStatus.COMPLETE, input.status, "skipped ${v.name()}")
        }
    }

    // --- replay / expectation helpers ----------------------------------------

    private fun replay(os: OStream, f: JsonObject) {
        val id = f["id"]?.jsonPrimitive?.content?.toInt() ?: 0
        when (val op = f.str("op")) {
            "unsigned" -> os.writeUnsigned(id, f.str("value").toULong().toLong())
            "signed" -> os.writeSigned(id, f.str("value").toLong())
            "boolean" -> os.writeBoolean(id, f.str("value").toBoolean())
            "fp32" -> os.writeFp32(id, floatOf(f["value"]!!))
            "fp64" -> os.writeFp64(id, doubleOf(f["value"]!!))
            "string" -> os.writeString(id, f.str("value"))
            "blob" -> os.writeBlob(id, unhex(f.str("value_hex")))
            "array" -> writeArray(os, id, f.str("element_type"), f.arr("values"))
            // The vectors' `serialized` hex is the DENSE image, which always carries
            // the frame — including for the empty-sequence vectors. Replaying through
            // the raw encoder therefore closes with the frame-keeping form:
            // writeSequenceEnd() would drop a contentless sequence and those vectors
            // would encode to nothing (MESSAGE_SPEC §2).
            "sequence_begin" -> os.writeSequenceBeginLazy(id)
            "sequence_end" -> os.writeSequenceEndKeep()
            else -> throw IllegalArgumentException("unknown op $op")
        }
    }

    private fun writeArray(os: OStream, id: Int, elemType: String, values: JsonArray) {
        val n = values.size
        when (elemType) {
            "u8", "i8" -> {
                val a = ByteArray(n) { longOf(values[it]).toByte() }
                if (elemType[0] == 'u') os.writeArrayUnsigned(id, a) else os.writeArraySigned(id, a)
            }
            "u16", "i16" -> {
                val a = ShortArray(n) { longOf(values[it]).toShort() }
                if (elemType[0] == 'u') os.writeArrayUnsigned(id, a) else os.writeArraySigned(id, a)
            }
            "u32", "i32" -> {
                val a = IntArray(n) { longOf(values[it]).toInt() }
                if (elemType[0] == 'u') os.writeArrayUnsigned(id, a) else os.writeArraySigned(id, a)
            }
            "u64", "i64" -> {
                val a = LongArray(n) { longOf(values[it]) }
                if (elemType[0] == 'u') os.writeArrayUnsigned(id, a) else os.writeArraySigned(id, a)
            }
            "fp32" -> os.writeArrayFp32(id, FloatArray(n) { floatOf(values[it]) })
            "fp64" -> os.writeArrayFp64(id, DoubleArray(n) { doubleOf(values[it]) })
            else -> throw IllegalArgumentException("unknown element_type $elemType")
        }
    }

    /** The event list a vector's fields[] must produce, in [RecordingVisitor]'s form. */
    private fun expectedEvents(v: JsonObject): List<String> {
        val ev = ArrayList<String>()
        for (f in v.arr("fields")) appendExpected(ev, f.jsonObject)
        return ev
    }

    private fun appendExpected(ev: MutableList<String>, f: JsonObject) {
        val id = f["id"]?.jsonPrimitive?.content?.toInt() ?: 0
        when (val op = f.str("op")) {
            "unsigned" -> ev.add("u:$id:${f.str("value").toULong()}")
            "signed" -> ev.add("s:$id:${f.str("value").toLong()}")
            "boolean" -> ev.add("u:$id:${if (f.str("value").toBoolean()) 1 else 0}")
            "fp32" -> ev.add("f32:$id:${floatOf(f["value"]!!).toRawBits()}")
            "fp64" -> ev.add("f64:$id:${doubleOf(f["value"]!!).toRawBits()}")
            "string" -> ev.add("str:$id:${f.str("value")}")
            "blob" -> ev.add("blob:$id:${f.str("value_hex").lowercase()}")
            "array" -> expectedArray(ev, id, f.str("element_type"), f.arr("values"))
            "sequence_begin" -> ev.add("seq{:$id")
            "sequence_end" -> ev.add("seq}")
            else -> throw IllegalArgumentException("unknown op $op")
        }
    }

    private fun expectedArray(ev: MutableList<String>, id: Int, elemType: String, values: JsonArray) {
        val kind = when {
            elemType == "fp32" -> ArrayKind.FP32
            elemType == "fp64" -> ArrayKind.FP64
            elemType[0] == 'u' -> ArrayKind.UNSIGNED
            else -> ArrayKind.SIGNED
        }
        ev.add("arr:$id:$kind:${values.size}")
        for (el in values) {
            when (elemType) {
                // Each width zero- or sign-extends to what the decoder delivers.
                "u8" -> ev.add("u:$id:${(longOf(el).toByte().toLong() and 0xFF).toULong()}")
                "u16" -> ev.add("u:$id:${(longOf(el).toShort().toLong() and 0xFFFF).toULong()}")
                "u32" -> ev.add("u:$id:${(longOf(el).toInt().toLong() and 0xFFFF_FFFFL).toULong()}")
                "u64" -> ev.add("u:$id:${longOf(el).toULong()}")
                "i8" -> ev.add("s:$id:${longOf(el).toByte().toLong()}")
                "i16" -> ev.add("s:$id:${longOf(el).toShort().toLong()}")
                "i32" -> ev.add("s:$id:${longOf(el).toInt().toLong()}")
                "i64" -> ev.add("s:$id:${longOf(el)}")
                "fp32" -> ev.add("f32:$id:${floatOf(el).toRawBits()}")
                "fp64" -> ev.add("f64:$id:${doubleOf(el).toRawBits()}")
                else -> throw IllegalArgumentException("unknown element_type $elemType")
            }
        }
    }

    /** [expectedEvents] with the skipped ids — and skipped sub-trees — removed. */
    private fun expectedEventsWithSkip(v: JsonObject, skip: Set<Int>): List<String> {
        val ev = ArrayList<String>()
        var depth = 0
        var skipUntil = -1
        for (fe in v.arr("fields")) {
            val f = fe.jsonObject
            val id = f["id"]?.jsonPrimitive?.content?.toInt() ?: 0
            when (f.str("op")) {
                "sequence_begin" -> {
                    if (skipUntil < 0 && id in skip) skipUntil = depth else if (skipUntil < 0) ev.add("seq{:$id")
                    depth++
                }
                "sequence_end" -> {
                    depth--
                    if (skipUntil >= 0) {
                        if (depth == skipUntil) skipUntil = -1
                    } else {
                        ev.add("seq}")
                    }
                }
                else -> if (skipUntil < 0 && id !in skip) appendExpected(ev, f)
            }
        }
        return ev
    }

    /** Drops the ids in [skip] and everything under a skipped sequence. */
    private class SkipVisitor(private val skip: Set<Int>) : Visitor {
        val out = RecordingVisitor()
        private var depth = 0
        private var skipUntil = -1

        private fun keep(id: Int) = skipUntil < 0 && id !in skip

        override fun unsigned(id: Int, value: Long) {
            if (keep(id)) out.unsigned(id, value)
        }

        override fun signed(id: Int, value: Long) {
            if (keep(id)) out.signed(id, value)
        }

        override fun fp32Bits(id: Int, bits: Int) {
            if (keep(id)) out.fp32Bits(id, bits)
        }

        override fun fp64(id: Int, value: Double) {
            if (keep(id)) out.fp64(id, value)
        }

        override fun string(id: Int, total: Int, offset: Int, data: ByteArray, chunkOffset: Int, chunkLength: Int) {
            if (keep(id)) out.string(id, total, offset, data, chunkOffset, chunkLength)
        }

        override fun blob(id: Int, total: Int, offset: Int, data: ByteArray, chunkOffset: Int, chunkLength: Int) {
            if (keep(id)) out.blob(id, total, offset, data, chunkOffset, chunkLength)
        }

        override fun arrayBegin(id: Int, kind: ArrayKind, count: Int) {
            if (keep(id)) out.arrayBegin(id, kind, count)
        }

        override fun sequenceBegin(id: Int) {
            if (skipUntil < 0 && id in skip) skipUntil = depth else if (skipUntil < 0) out.sequenceBegin(id)
            depth++
        }

        override fun sequenceEnd() {
            depth--
            if (skipUntil >= 0) {
                if (depth == skipUntil) skipUntil = -1
                return
            }
            out.sequenceEnd()
        }
    }

    /**
     * A consumer that materializes every string: it accumulates the payload and
     * validates it at completion, which is what §6.4 requires of generated code —
     * and what makes the outcome independent of where the chunks fell.
     */
    private class MaterializingStringVisitor : Visitor {
        private var buf = ByteArray(0)

        override fun string(id: Int, total: Int, offset: Int, data: ByteArray, chunkOffset: Int, chunkLength: Int) {
            if (offset == 0) buf = ByteArray(total)
            data.copyInto(buf, offset, chunkOffset, chunkOffset + chunkLength)
            if (offset + chunkLength >= total && !Utf8.valid(buf)) {
                throw SofabException(SofabError.INVALID_MSG, "invalid UTF-8 string payload")
            }
        }
    }
}

/** The shared vector file, parsed once for the whole suite. */
internal object Vectors {
    private val root: JsonObject = run {
        val path = System.getProperty("sofab.vectors") ?: "assets/test_vectors.json"
        val file = File(path)
        check(file.isFile) { "shared test vectors not found at $path" }
        Json.parseToJsonElement(file.readText()).jsonObject
    }

    val positive: List<JsonObject> = root["vectors"]!!.jsonArray.map { it.jsonObject }
    val invalidUtf8: List<JsonObject> = root["invalid_utf8"]?.jsonArray.orEmpty().map { it.jsonObject }

    init {
        check(root.str("format") == "sofabuffers-test-vectors") { "unexpected vector file format" }
    }
}

internal fun JsonObject.str(key: String): String = this[key]!!.jsonPrimitive.content
internal fun JsonObject.int(key: String): Int = this[key]?.jsonPrimitive?.content?.toInt() ?: 0
internal fun JsonObject.arr(key: String): JsonArray = this[key]!!.jsonArray
internal fun JsonObject.name(): String = str("name")
internal fun JsonObject.serializedHex(): String = this["serialized"]!!.jsonObject.str("hex")

/** A float value: a JSON number, or the literals "inf" / "-inf". */
internal fun floatOf(e: JsonElement): Float {
    val p = e.jsonPrimitive
    return if (p.isString) infOf(p) else p.content.toFloat()
}

internal fun doubleOf(e: JsonElement): Double {
    val p = e.jsonPrimitive
    return if (p.isString) infOf(p).toDouble() else p.content.toDouble()
}

private fun infOf(p: JsonPrimitive): Float = when (p.content) {
    "inf" -> Float.POSITIVE_INFINITY
    "-inf" -> Float.NEGATIVE_INFINITY
    else -> throw IllegalArgumentException("unexpected float literal ${p.content}")
}

/** An integer element: the full u64/i64 range, kept exact through its literal text. */
internal fun longOf(e: JsonElement): Long {
    val text = e.jsonPrimitive.content
    return text.toLongOrNull() ?: text.toULong().toLong()
}
